language: node_js
node_js:
  - "8"
cache: yarn
deploy:
  - on:
    branch: master
    tags: true
install:
  - yarn install
script: 
  - docker build -t fewbox/sample-istio-apigateway:$TRAVIS_TAG .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fewbox/sample-istio-apigateway:$TRAVIS_TAG